### ISSUE TITLE
Error after update to Nextjs 15

### ISSUE THREAD

**Issue by joncoronel** [Openpanel-dev/openpanel#81]
Updated to Nextjs 15 and it seems openpanel breaks after the update.     It seems to only occur in the turbo dev server. Does not occur in production. If I remove the `--turbo` from the dev server, it seems to work. Although, I did not get this error before upgrading even when using turbo before.  Simply importing `import { OpenPanelComponent } from "@openpanel/nextjs";` causes the following error to occur:
 ```
 TypeError: 'ownKeys' on proxy: trap returned extra keys but proxy target is non-extensible
    at Reflect.ownKeys (<anonymous>)
    at Object.ownKeys (C:\Users\jonny\Documents\bentome\.next\server\edge\chunks\ssr\edge-wrapper_099f8c.js:76:47)
    at getOwnPropertyNames (<anonymous>)
    at d (C:\Users\jonny\Documents\bentome\.next\server\edge\chunks\ssr\node_modules_089e05._.js:482:76)
    at c (C:\Users\jonny\Documents\bentome\.next\server\edge\chunks\ssr\node_modules_089e05._.js:487:112)
    at <unknown> (C:\Users\jonny\Documents\bentome\.next\server\edge\chunks\ssr\edge-wrapper_099f8c.js:693:27)
    at runModuleExecutionHooks (C:\Users\jonny\Documents\bentome\.next\server\edge\chunks\ssr\edge-wrapper_099f8c.js:738:9)
    at instantiateModule (C:\Users\jonny\Documents\bentome\.next\server\edge\chunks\ssr\edge-wrapper_099f8c.js:691:9)
    at getOrInstantiateModuleFromParent (C:\Users\jonny\Documents\bentome\.next\server\edge\chunks\ssr\edge-wrapper_099f8c.js:624:12)```

**Comment by lindesvard** [comment]
Thanks for the report. I'll have a look

**Comment by lindesvard** [comment]
Just tried on a fresh installation of nextjs 15 without any issues. Can you create a reproducible repo where I can check?

**Comment by joncoronel** [comment]
Okay, so tested a bit more and the error occurs when both `--turbo` is enabled and the root layout is set to `export const runtime = "edge";`.

**Comment by joncoronel** [comment]
https://github.com/joncoronel/vps-testing

Also replicated here. Fresh install of next 15 and react 19.

**Comment by lindesvard** [comment]
Great, I could reproduce the error now. Will give to solve this

**Comment by lindesvard** [comment]
Late on this but know the problem. Just need to dig a bit more since it breaks on nextjs pages folder if I do this change. Hang in there

**Comment by lindesvard** [comment]
Hopefully solves in version `@openpanel/nextjs@1.0.6`. Re-open otherwise
